TOPIC_CAMERA = "camera_data"
TOPIC_IMU = "imu_data"
TOPIC_ANDROID_IMU = "android_imu_data"
TOPIC_RECORD_TIMER = "record_timer"
TOPIC_TIME_DELAY = "time_delay"
TOPIC_MOTION_STATUS = "motion_status"
TOPIC_NODE_COOKIE = "node_cookie"

PORT_IMU = 16510
PORT_CAMERA = 16515
PORT_RECORD_TIMER = 16520
PORT_TIME_DELAY = 16521
PORT_MOTION_STATUS = 16525

DEFAULT_HOST = "127.0.0.1"
